### ISSUE TITLE
Cannot construct pre-training dataset

### ISSUE THREAD

**Issue by ardaboluk** [ShahinSHH/COVID-CAPS#1]
Hi,

1. Downloaded the images from https://nihcc.app.box.com/v/ChestXray-NIHCC/folder/37178474737 using batch_download_zips.py
2. As instructed in https://github.com/ShahinSHH/COVID-CAPS/tree/master/database, extracted each zip archive to its corresponding directory database/images_0**/
3. Ran xray14_preprocess.py. This created database_preprocessed which contains images.
4. Ran xray14_selection.py. This created X_image.npy (which I renamed as X_images.npy) and Y_labels.npy.
5. Ran pre-train.py, which gives the following error:

```
Traceback (most recent call last):
  File "pre-train.py", line 142, in <module>
    x = Capsule(32, 8, 3, True)(x)  
  File "/home/arda/Programs/py3_envs/tfenv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/arda/Programs/py3_envs/tfenv/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    pre-train.py:109 call  *
        b = keras.backend.batch_dot(o, hat_inputs, [2, 3])
    /home/arda/Programs/py3_envs/tfenv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1496 batch_dot  *
        raise ValueError('Can not do batch_dot on inputs with shapes ' +

    ValueError: Can not do batch_dot on inputs with shapes (None, 32, 32, 8) and (None, 32, None, 8) with axes=[2, 3]. x.shape[2] != y.shape[3] (32 != 8).
```

Thanks.

**Comment by ShahinSHH** [comment]
Good day,
Hope you are doing well.

Firstly, make sure that your tensorflow and Keras versions are the same as indicated in the page. (tensorflow-gpu 2 and keras-gpu 2.2.4)
If you’re not using gpu you can use tensorflow 1.14 and Keras 2.2.4 (I tested them and they work).

Secondly, if after changing the versions the problem is still unfixed, try using keras instead of tensorflow.keras in the importing section of the code. This will fix the error.

I hope this can solve your problem. If you have more questions feel free to ask me.

Best,
Shahin

**Comment by ardaboluk** [comment]
Thank you. Changing the Keras version solved the problem.

**Comment by rezacsedu** [comment]
@ShahinSHH, with TensorFlow 1.14 and Keras 2.2.4, I get the following error: 

`TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (1, Dimension(128), 256). Consider casting elements to a supported type. `

**Comment by ShahinSHH** [comment]
Do you know which line of code cause this error?

**Comment by rezacsedu** [comment]
@ShahinSHH, the folowing line seems problematic:

`x = Reshape((-1, 128))(x) `

However, switching to another CapsNet implementation (i.e., https://github.com/maxjcohen/CapsNet-for-Keras) has fixed the problem.

**Comment by ShahinSHH** [comment]
Great
BTW, try using keras instead of tensorflow.keras in the importing section of the code at the very beginning. In some cases it fixed the same problem you have.
